### PR TITLE
Mathjax node 2.5.1

### PR DESCRIPTION
**Pull request by physikerwelt**
Mathoid 0.2.6 was using the branch mathjax/MathJax#mathjax-node-2.5
(https://github.com/wikimedia/MathJax-node/blob/mathoid-0-2-6/package.json#L24)
In the same spirit mathoid 0.2.8. should use the corresponding 2.5.1 branch with additional tweaks such as https://github.com/mathjax/MathJax/issues/1201

### CODE REVIEW

**Comment by physikerwelt** [comment]
@d00rman @gwicke please merge

**Comment by physikerwelt** [comment]
#5 is the follow up

**Comment by d00rman** [comment]
It's not clear to me from this PR what the differences are, and how that improves/changes mathoid's behaviour

**Comment by gwicke** [comment]
With a large changeset like this we probably can't ensure that things are fine purely based on code review. We'll have to budget sufficient time for testing before deploy.

When is the next mathoid deploy planned, and do we have the time to test before then?

**Comment by physikerwelt** [comment]
the pull request is for the 0-2-8 branch. When we switch to this branch will be determined by https://gerrit.wikimedia.org/r/#/c/218350/ ... in conclusion I think it's save to just self merge the changes that remove a log of unused files

**Comment by gwicke** [comment]
@physikerwelt: okay, sounds good to me. Also overlooked that it's not a general update, but really only deletions.

**Pull request merged**
